#!/usr/bin/env python3
"""Regenerate the derived files in study/ from their in-repo sources.

The Claude Project pack in study/ is partly hand-written and partly derived. This
script rebuilds the derived half so the pack cannot drift from the site:

    study/prompts.md                       <- data/study_prompts.yaml
    study/knowledge/01-oz-finance-primer.md <- dist/learn/index.html
    study/knowledge/02-capital-stack.md    <- dist/capital-stack/index.html
    study/knowledge/03-cra-oz-overlap-brief.md <- docs/cra-oz-overlap-brief.md
    study/knowledge/05-references-finance.md   <- references.md sections 1, 6, 7, 8, 14
    study/knowledge/06-glossary.md         <- data/glossary.yaml

Hand-written and left alone: study/README.md, study/project-instructions.md,
study/knowledge/00-how-to-use.md, study/knowledge/04-key-figures.md.

The two page exports read the built HTML rather than parsing .astro templates, so
run `npm run build` first. Re-runnable and idempotent.

Usage:
    python3 scripts/export_study_pack.py
"""

from __future__ import annotations

import re
import sys
from html import unescape
from html.parser import HTMLParser
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
STUDY = ROOT / "study"
KNOWLEDGE = STUDY / "knowledge"

# references.md sections that carry the finance/capital/CRA/tax-mechanics sources.
REFERENCE_SECTIONS = (1, 6, 7, 8, 14)

BANNER = (
    "<!-- GENERATED by scripts/export_study_pack.py from {source}. "
    "Do not edit by hand — edit the source and re-run the script. -->"
)


# --------------------------------------------------------------------------- HTML


class MarkdownExtractor(HTMLParser):
    """Convert the <main> content of a built Astro page into readable markdown.

    Deliberately narrow: it handles the tags these pages actually use (headings,
    paragraphs, lists, tables, definition lists, inline emphasis and links) and
    drops everything visual. SVG, script, and style subtrees are skipped whole —
    the diagrams carry their meaning in an aria-label, which is emitted instead.
    """

    SKIP = {"svg", "script", "style", "noscript", "button", "nav"}
    BLOCK = {
        "p", "div", "section", "figcaption", "li", "dt", "dd",
        "h1", "h2", "h3", "h4", "tr", "figure", "ol", "ul", "dl", "table",
    }

    SITE = "https://oz2.vargo.city"

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.out: list[str] = []
        self.buf: list[str] = []
        self._skip_depth = 0
        self._skip_tag: str | None = None
        self._in_main = False
        self._list_stack: list[str] = []
        self._row: list[str] | None = None
        self._table_rows: list[list[str]] | None = None
        self._header_row = False
        self._pending_prefix = ""
        # (buffer length at open, absolute href) — href None means "do not linkify"
        self._link_stack: list[tuple[int, str | None]] = []

    # -- helpers

    def _flush(self) -> None:
        text = re.sub(r"\s+", " ", "".join(self.buf)).strip()
        self.buf.clear()
        if not text or re.fullmatch(r"\d{1,2}", text):
            # Bare numerals are the module eyebrows ("01"…"06"), meaningless here.
            self._pending_prefix = ""
            return
        self.out.append(self._pending_prefix + text)
        self._pending_prefix = ""

    def _emit(self, text: str) -> None:
        self.out.append(text)

    # -- parser hooks

    def handle_starttag(self, tag: str, attrs_list) -> None:
        attrs = dict(attrs_list)

        if self._skip_depth:
            if tag == self._skip_tag:
                self._skip_depth += 1
            return

        if tag in self.SKIP:
            self._skip_depth = 1
            self._skip_tag = tag
            # A diagram's accessible description is the only part worth keeping.
            if tag == "svg" and attrs.get("aria-label"):
                self._flush()
                self._emit(f"*[Diagram: {attrs['aria-label']}]*")
            return

        if tag == "main":
            self._in_main = True
            return
        if not self._in_main:
            return

        if tag in self.BLOCK:
            self._flush()

        if tag in ("h1", "h2", "h3", "h4"):
            self._pending_prefix = "#" * int(tag[1]) + " "
        elif tag in ("ul", "ol"):
            self._list_stack.append(tag)
        elif tag == "li":
            marker = "- " if (self._list_stack or ["ul"])[-1] == "ul" else "1. "
            self._pending_prefix = "  " * max(0, len(self._list_stack) - 1) + marker
        elif tag == "dt":
            self._pending_prefix = "**"
        elif tag == "table":
            self._table_rows = []
        elif tag == "tr" and self._table_rows is not None:
            self._row = []
            self._header_row = False
        elif tag == "th":
            self._header_row = True
        elif tag in ("strong", "b", "em", "i", "code"):
            self.buf.append("*" if tag in ("em", "i") else "**" if tag in ("strong", "b") else "`")
        elif tag == "a":
            href = attrs.get("href", "")
            if href.startswith("/"):
                href = self.SITE + href
            elif not href.startswith(("http://", "https://")):
                # In-page anchors and the like carry nothing useful in a text export.
                href = ""
            if href:
                self.buf.append("[")
                self._link_stack.append((len(self.buf), href))
            else:
                self._link_stack.append((len(self.buf), None))

    def handle_endtag(self, tag: str) -> None:
        if self._skip_depth:
            if tag == self._skip_tag:
                self._skip_depth -= 1
                if self._skip_depth == 0:
                    self._skip_tag = None
            return

        if tag == "main":
            self._flush()
            self._in_main = False
            return
        if not self._in_main:
            return

        if tag in ("strong", "b", "em", "i", "code"):
            self.buf.append("*" if tag in ("em", "i") else "**" if tag in ("strong", "b") else "`")
            return

        if tag == "a":
            if not self._link_stack:
                return
            start, href = self._link_stack.pop()
            if href is None:
                return
            if "".join(self.buf[start:]).strip():
                self.buf.append(f"]({href})")
            else:
                # Empty link text — the anchor-link copy icons. Drop the stray bracket.
                del self.buf[start - 1:]
            return

        if tag in ("th", "td") and self._row is not None:
            cell = re.sub(r"\s+", " ", "".join(self.buf)).strip()
            self.buf.clear()
            self._row.append(cell.replace("|", "\\|"))
            return

        if tag == "tr" and self._table_rows is not None and self._row is not None:
            if any(self._row):
                self._table_rows.append(self._row)
                if self._header_row and len(self._table_rows) == 1:
                    self._table_rows.append(["---"] * len(self._row))
            self._row = None
            return

        if tag == "table" and self._table_rows is not None:
            self._flush()
            width = max((len(r) for r in self._table_rows), default=0)
            for row in self._table_rows:
                padded = row + [""] * (width - len(row))
                self._emit("| " + " | ".join(padded) + " |")
            self._table_rows = None
            return

        if tag == "dt":
            self.buf.append("**")

        if tag in ("ul", "ol") and self._list_stack:
            self._flush()
            self._list_stack.pop()
            return

        if tag in self.BLOCK:
            self._flush()

    def handle_data(self, data: str) -> None:
        if self._skip_depth or not self._in_main:
            return
        if self._row is not None or self._table_rows is None:
            self.buf.append(data)
        else:
            # Text sitting directly inside a table but outside a cell — ignore.
            pass

    def result(self) -> str:
        self._flush()
        lines: list[str] = []
        for block in self.out:
            block = unescape(block).strip()
            if not block:
                continue
            if lines and lines[-1].startswith("|") and block.startswith("|"):
                lines.append(block)
            else:
                if lines:
                    lines.append("")
                lines.append(block)
        return "\n".join(lines).strip() + "\n"


def html_to_markdown(path: Path, stop_before: str | None = None) -> str:
    html = path.read_text(encoding="utf8")
    if stop_before:
        idx = html.find(stop_before)
        if idx == -1:
            raise SystemExit(f"{path}: expected to find {stop_before!r} to truncate at")
        html = html[:idx] + "</main>"
    parser = MarkdownExtractor()
    parser.feed(html)
    return parser.result()


# ------------------------------------------------------------------- generators


def write(path: Path, body: str, source: str) -> bool:
    """Write body with a generated-from banner. Returns True if the file changed."""
    content = BANNER.format(source=source) + "\n\n" + body.rstrip() + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    previous = path.read_text(encoding="utf8") if path.exists() else None
    if previous == content:
        print(f"  unchanged  {path.relative_to(ROOT)}")
        return False
    path.write_text(content, encoding="utf8")
    print(f"  wrote      {path.relative_to(ROOT)}")
    return True


def gen_prompts() -> bool:
    prompts = yaml.safe_load((ROOT / "data/study_prompts.yaml").read_text(encoding="utf8"))
    modules: dict[str, str] = {
        "tax-incentive": "1. How the tax incentive actually works",
        "capital-stacks": "2. Reading a capital stack",
        "banks-and-cra": "3. Banks and the Community Reinvestment Act",
        "cdfis": "4. CDFIs",
        "deal-economics": "5. Deal economics",
        "evidence-check": "6. The evidence check",
    }
    unknown = {p["module"] for p in prompts} - set(modules)
    if unknown:
        raise SystemExit(f"data/study_prompts.yaml: unknown module(s) {sorted(unknown)}")

    lines = [
        "# Study prompts",
        "",
        f"{len(prompts)} prompts across six modules, written to make something teach you rather",
        "than recite at you. Paste one into a conversation with the OZ Finance Tutor project",
        "(see ../README.md for setup), or into any chat.",
        "",
        "The matching curriculum is at https://oz2.vargo.city/learn",
    ]
    for module_id, heading in modules.items():
        lines += ["", f"## {heading}"]
        for p in (x for x in prompts if x["module"] == module_id):
            lines += ["", f"### {p['id']}", "", "> " + " ".join(p["prompt"].split()), "", f"*{p['why']}*"]
            if p.get("followups"):
                lines += ["", "Follow-ups:"]
                lines += [f"- {f}" for f in p["followups"]]
    return write(STUDY / "prompts.md", "\n".join(lines), "data/study_prompts.yaml")


def gen_glossary() -> bool:
    terms = yaml.safe_load((ROOT / "data/glossary.yaml").read_text(encoding="utf8"))
    terms.sort(key=lambda t: re.sub(r"^[^0-9A-Za-z]+", "", t["term"]).lower())

    lines = [
        "# Glossary",
        "",
        "Terms and acronyms used across the OZ finance material.",
    ]
    for t in terms:
        head = f"## {t['term']}"
        if t.get("expansion"):
            head += f" — {t['expansion']}"
        lines += ["", head, "", " ".join(t["definition"].split())]
        extras = []
        if t.get("see_also"):
            extras.append("See also: " + ", ".join(t["see_also"]) + ".")
        if t.get("site_link"):
            extras.append(f"In context: https://oz2.vargo.city{t['site_link']}")
        if extras:
            lines += ["", "*" + " ".join(extras) + "*"]
    return write(KNOWLEDGE / "06-glossary.md", "\n".join(lines), "data/glossary.yaml")


def gen_cra_brief() -> bool:
    body = (ROOT / "docs/cra-oz-overlap-brief.md").read_text(encoding="utf8")
    return write(KNOWLEDGE / "03-cra-oz-overlap-brief.md", body, "docs/cra-oz-overlap-brief.md")


def gen_references() -> bool:
    text = (ROOT / "references.md").read_text(encoding="utf8")
    # Split on level-2 headings, keeping the heading with its body.
    parts = re.split(r"^## ", text, flags=re.M)
    wanted: list[str] = []
    for part in parts[1:]:
        m = re.match(r"(\d+)\.", part)
        if m and int(m.group(1)) in REFERENCE_SECTIONS:
            wanted.append("## " + part.rstrip())
    found = len(wanted)
    if found != len(REFERENCE_SECTIONS):
        raise SystemExit(
            f"references.md: found {found} of {len(REFERENCE_SECTIONS)} expected sections "
            f"{REFERENCE_SECTIONS} — check the heading numbering"
        )
    header = [
        "# Finance bibliography",
        "",
        "The finance, capital, CDFI, CRA, NMTC, and tax-mechanics sections of the project",
        f"bibliography — sections {', '.join(str(s) for s in REFERENCE_SECTIONS)} of references.md.",
        "Every `last_checked` date is the date that source was last verified.",
        "",
        "Full bibliography: https://oz2.vargo.city/references",
    ]
    return write(
        KNOWLEDGE / "05-references-finance.md",
        "\n".join(header) + "\n\n" + "\n\n".join(wanted),
        "references.md sections " + ", ".join(str(s) for s in REFERENCE_SECTIONS),
    )


def gen_primer() -> bool:
    src = ROOT / "dist/learn/index.html"
    require_build(src)
    # Everything up to the prompt library; prompts and glossary ship as their own files.
    body = html_to_markdown(src, stop_before='<section id="prompts"')
    return write(KNOWLEDGE / "01-oz-finance-primer.md", body, "the built /learn page")


def gen_capital_stack() -> bool:
    src = ROOT / "dist/capital-stack/index.html"
    require_build(src)
    return write(KNOWLEDGE / "02-capital-stack.md", html_to_markdown(src), "the built /capital-stack page")


def require_build(path: Path) -> None:
    if not path.exists():
        raise SystemExit(
            f"missing {path.relative_to(ROOT)} — run `npm run build` first, "
            "then re-run this script"
        )


def main() -> int:
    print("Exporting study pack...")
    changed = [
        gen_prompts(),
        gen_glossary(),
        gen_cra_brief(),
        gen_references(),
        gen_primer(),
        gen_capital_stack(),
    ]
    n = sum(changed)
    print(f"Done — {n} file(s) changed, {len(changed) - n} already current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
